import type { ContentItem } from './types'

const v = (
  id: string,
  italian: string,
  english: string,
  topic: string,
  register: ContentItem['register'],
  difficulty: ContentItem['difficulty'],
  region?: ContentItem['region'],
  notes?: string
): ContentItem => ({
  id: `vocab:${topic}:${id}`,
  type: 'vocab',
  language: 'italian',
  italian,
  english,
  audioUrl: '',
  topic,
  register,
  difficulty,
  region,
  notes,
})

export const italianVocab: ContentItem[] = [
  v('buongiorno', 'buongiorno', 'good morning / hello', 'greeting', 'formal', 1, undefined, 'Standard polite greeting until ~5pm. Safe with strangers, hotel staff, shopkeepers.'),
  v('buonasera', 'buonasera', 'good evening', 'greeting', 'formal', 1, undefined, 'After ~5pm or whenever evening atmosphere starts.'),
  v('buonanotte', 'buonanotte', 'good night', 'greeting', 'both', 1, undefined, 'Only when parting at night, never as hello.'),
  v('ciao', 'ciao', 'hi / bye (informal)', 'greeting', 'informal', 1, undefined, 'Never with strangers in formal settings — sounds like calling them by their first name.'),
  v('salve', 'salve', 'hello (neutral)', 'greeting', 'both', 2, undefined, 'A useful in-between if you want polite without buongiorno.'),
  v('arrivederci', 'arrivederci', 'goodbye', 'greeting', 'formal', 1),
  v('a-presto', 'a presto', 'see you soon', 'greeting', 'both', 1),
  v('grazie', 'grazie', 'thank you', 'social', 'both', 1),
  v('grazie-mille', 'grazie mille', 'thanks a lot', 'social', 'both', 1),
  v('prego', 'prego', "you're welcome / please go ahead / can I help you", 'social', 'both', 1, undefined, 'Multi-purpose. Shopkeeper says it as "what can I do for you", you say it back as "thanks/welcome".'),
  v('per-favore', 'per favore', 'please', 'social', 'both', 1),
  v('mi-scusi', 'mi scusi', 'excuse me (formal)', 'social', 'formal', 1, undefined, 'Lei form. Use with strangers, waiters.'),
  v('scusa', 'scusa', 'excuse me / sorry (informal)', 'social', 'informal', 1),
  v('mi-dispiace', 'mi dispiace', "I'm sorry", 'social', 'both', 1, undefined, 'For sympathy or apology. Stronger than just scusa.'),
  v('non-capisco', 'non capisco', "I don't understand", 'social', 'both', 1),
  v('parla-inglese', 'parla inglese?', 'do you speak English? (formal)', 'social', 'formal', 1),
  v('come-si-dice', 'come si dice...?', 'how do you say...?', 'social', 'both', 2),
  v('si', 'sì', 'yes', 'social', 'both', 1),
  v('no', 'no', 'no', 'social', 'both', 1),
  v('forse', 'forse', 'maybe', 'social', 'both', 1),
  v('certo', 'certo', 'of course / sure', 'social', 'both', 1),
  v('va-bene', 'va bene', 'okay / fine', 'social', 'both', 1),

  v('il-conto', 'il conto', 'the bill / check', 'restaurant', 'both', 1, undefined, 'Wait staff will not bring the bill unless asked — this is THE phrase to know.'),
  v('una-tavola', 'un tavolo per due', 'a table for two', 'restaurant', 'formal', 1, undefined, 'Tavolo (the piece of furniture) not tavola (set table).'),
  v('il-menu', 'il menù', 'the menu', 'restaurant', 'both', 1),
  v('la-carta-vini', 'la carta dei vini', 'the wine list', 'restaurant', 'both', 2),
  v('lacqua', "l'acqua", 'water', 'restaurant', 'both', 1),
  v('frizzante', 'frizzante', 'sparkling', 'restaurant', 'both', 1, undefined, 'For water: acqua frizzante. Default in Italian restaurants is naturale (still) — must specify.'),
  v('naturale', 'naturale', 'still (water)', 'restaurant', 'both', 1),
  v('un-caffe', 'un caffè', 'an espresso', 'restaurant', 'both', 1, undefined, '"Caffè" alone always means espresso in Italy. Cappuccino is a breakfast-only drink — locals do not order it after 11am.'),
  v('un-cappuccino', 'un cappuccino', 'a cappuccino', 'restaurant', 'both', 1),
  v('un-bicchiere-di', 'un bicchiere di vino', 'a glass of wine', 'restaurant', 'both', 1),
  v('una-bottiglia', 'una bottiglia', 'a bottle', 'restaurant', 'both', 1),
  v('rosso', 'rosso', 'red (wine)', 'restaurant', 'both', 1),
  v('bianco', 'bianco', 'white (wine)', 'restaurant', 'both', 1),
  v('lantipasto', "l'antipasto", 'starter / appetizer', 'restaurant', 'both', 1),
  v('il-primo', 'il primo', 'first course (pasta/risotto/soup)', 'restaurant', 'both', 1, undefined, 'Italian meals: antipasto → primo → secondo → contorno → dolce. You do not have to order all of them.'),
  v('il-secondo', 'il secondo', 'second course (meat/fish)', 'restaurant', 'both', 1),
  v('il-contorno', 'il contorno', 'side dish', 'restaurant', 'both', 1, undefined, 'Vegetables come as a separate course/order — a secondo of meat does NOT come with vegetables on the plate.'),
  v('il-dolce', 'il dolce', 'dessert', 'restaurant', 'both', 1),
  v('allergico', 'sono allergico/a a...', 'I am allergic to...', 'restaurant', 'both', 1, undefined, 'Use allergico (m) or allergica (f). Critical for shellfish/nuts.'),
  v('vegetariano', 'sono vegetariano/a', 'I am vegetarian', 'restaurant', 'both', 1),
  v('senza', 'senza', 'without', 'restaurant', 'both', 1, undefined, 'senza glutine = without gluten. senza latte = without dairy. senza cipolla = without onion.'),
  v('coperto', 'il coperto', 'cover charge', 'restaurant', 'both', 2, undefined, 'Per-person charge added to bills, especially in tourist areas. Normal, not a scam.'),
  v('da-portare-via', 'da portare via', 'to take away / to-go', 'restaurant', 'both', 2),
  v('squisito', 'squisito', 'delicious', 'restaurant', 'both', 2),

  v('la-chiave', 'la chiave', 'the key', 'hotel', 'both', 1),
  v('la-camera', 'la camera', 'the room', 'hotel', 'both', 1),
  v('la-colazione', 'la colazione', 'breakfast', 'hotel', 'both', 1),
  v('inclusa', 'è inclusa?', 'is it included?', 'hotel', 'formal', 1, undefined, 'For asking if breakfast is included.'),
  v('check-in', 'il check-in', 'check-in', 'hotel', 'both', 1),
  v('check-out', 'il check-out', 'check-out', 'hotel', 'both', 1),
  v('prenotazione', 'una prenotazione', 'a reservation', 'hotel', 'formal', 1),
  v('a-nome-di', 'a nome di...', 'under the name of...', 'hotel', 'formal', 1),
  v('il-wifi', 'il wifi', 'the wifi', 'hotel', 'both', 1),
  v('la-password', 'la password', 'the password', 'hotel', 'both', 1),
  v('un-asciugamano', 'un asciugamano', 'a towel', 'hotel', 'both', 1),
  v('laria-condizionata', "l'aria condizionata", 'air conditioning', 'hotel', 'both', 2),
  v('il-riscaldamento', 'il riscaldamento', 'the heating', 'hotel', 'both', 2),
  v('non-funziona', 'non funziona', "it doesn't work", 'hotel', 'both', 1),

  v('il-treno', 'il treno', 'train', 'transport', 'both', 1),
  v('un-biglietto', 'un biglietto', 'a ticket', 'transport', 'both', 1),
  v('andata', 'andata', 'one-way', 'transport', 'both', 1),
  v('andata-e-ritorno', 'andata e ritorno', 'round-trip', 'transport', 'both', 1),
  v('il-binario', 'il binario', 'the platform', 'transport', 'both', 1),
  v('in-ritardo', 'in ritardo', 'late / delayed', 'transport', 'both', 1),
  v('soppresso', 'soppresso', 'cancelled', 'transport', 'both', 2),
  v('a-che-ora', 'a che ora?', 'at what time?', 'transport', 'both', 1),
  v('parte', 'parte', 'it leaves', 'transport', 'both', 1),
  v('arriva', 'arriva', 'it arrives', 'transport', 'both', 1),
  v('il-traghetto', 'il traghetto', 'ferry', 'transport', 'both', 1, 'sardinia', 'You will need this for Sardinia.'),
  v('il-taxi', 'il taxi', 'taxi', 'transport', 'both', 1),
  v('lautobus', "l'autobus", 'bus', 'transport', 'both', 1),
  v('la-fermata', 'la fermata', 'the bus stop', 'transport', 'both', 1),
  v('il-parcheggio', 'il parcheggio', 'parking', 'transport', 'both', 1),
  v('a-piedi', 'a piedi', 'on foot', 'transport', 'both', 2),

  v('a-destra', 'a destra', 'right', 'directions', 'both', 1),
  v('a-sinistra', 'a sinistra', 'left', 'directions', 'both', 1),
  v('sempre-dritto', 'sempre dritto', 'straight ahead', 'directions', 'both', 1),
  v('vicino', 'vicino', 'near', 'directions', 'both', 1),
  v('lontano', 'lontano', 'far', 'directions', 'both', 1),
  v('qui', 'qui', 'here', 'directions', 'both', 1),
  v('li', 'lì', 'there', 'directions', 'both', 1),
  v('langolo', "all'angolo", 'on the corner', 'directions', 'both', 2),
  v('di-fronte-a', 'di fronte a', 'across from', 'directions', 'both', 2),
  v('accanto-a', 'accanto a', 'next to', 'directions', 'both', 2),
  v('si-puo-andare', 'si può andare a piedi?', 'can one walk there?', 'directions', 'both', 2),
  v('quanto-dista', 'quanto dista?', 'how far is it?', 'directions', 'both', 2),
  v('mi-sono-perso', 'mi sono perso/a', "I'm lost", 'directions', 'both', 2),

  v('uno', 'uno', 'one', 'numbers', 'both', 1),
  v('due', 'due', 'two', 'numbers', 'both', 1),
  v('tre', 'tre', 'three', 'numbers', 'both', 1),
  v('quattro', 'quattro', 'four', 'numbers', 'both', 1),
  v('cinque', 'cinque', 'five', 'numbers', 'both', 1),
  v('sei', 'sei', 'six', 'numbers', 'both', 1),
  v('sette', 'sette', 'seven', 'numbers', 'both', 1),
  v('otto', 'otto', 'eight', 'numbers', 'both', 1),
  v('nove', 'nove', 'nine', 'numbers', 'both', 1),
  v('dieci', 'dieci', 'ten', 'numbers', 'both', 1),
  v('venti', 'venti', 'twenty', 'numbers', 'both', 1),
  v('trenta', 'trenta', 'thirty', 'numbers', 'both', 1),
  v('cento', 'cento', 'one hundred', 'numbers', 'both', 1),
  v('mille', 'mille', 'one thousand', 'numbers', 'both', 1),

  v('ieri', 'ieri', 'yesterday', 'time', 'both', 1),
  v('oggi', 'oggi', 'today', 'time', 'both', 1),
  v('domani', 'domani', 'tomorrow', 'time', 'both', 1),
  v('adesso', 'adesso', 'now', 'time', 'both', 1),
  v('dopo', 'dopo', 'after / later', 'time', 'both', 1),
  v('prima', 'prima', 'before / earlier', 'time', 'both', 1),
  v('mattina', 'la mattina', 'morning', 'time', 'both', 1),
  v('pomeriggio', 'il pomeriggio', 'afternoon', 'time', 'both', 1),
  v('sera', 'la sera', 'evening', 'time', 'both', 1),
  v('notte', 'la notte', 'night', 'time', 'both', 1),
  v('lunedi', 'lunedì', 'Monday', 'time', 'both', 1),
  v('martedi', 'martedì', 'Tuesday', 'time', 'both', 1),
  v('mercoledi', 'mercoledì', 'Wednesday', 'time', 'both', 1),
  v('giovedi', 'giovedì', 'Thursday', 'time', 'both', 1),
  v('venerdi', 'venerdì', 'Friday', 'time', 'both', 1),
  v('sabato', 'sabato', 'Saturday', 'time', 'both', 1),
  v('domenica', 'domenica', 'Sunday', 'time', 'both', 1),

  v('il-pane', 'il pane', 'bread', 'food', 'both', 1),
  v('il-formaggio', 'il formaggio', 'cheese', 'food', 'both', 1),
  v('il-prosciutto', 'il prosciutto', 'ham / prosciutto', 'food', 'both', 1),
  v('luovo', "l'uovo", 'egg', 'food', 'both', 1),
  v('la-carne', 'la carne', 'meat', 'food', 'both', 1),
  v('il-pesce', 'il pesce', 'fish', 'food', 'both', 1),
  v('il-pollo', 'il pollo', 'chicken', 'food', 'both', 1),
  v('il-manzo', 'il manzo', 'beef', 'food', 'both', 1),
  v('lagnello', "l'agnello", 'lamb', 'food', 'both', 2),
  v('le-verdure', 'le verdure', 'vegetables', 'food', 'both', 1),
  v('lolio', "l'olio d'oliva", 'olive oil', 'food', 'both', 1),
  v('il-sale', 'il sale', 'salt', 'food', 'both', 1),
  v('il-pepe', 'il pepe', 'pepper', 'food', 'both', 1),
  v('la-bistecca', 'la bistecca alla fiorentina', 'Florentine T-bone steak', 'food', 'both', 2, 'tuscany', 'Iconic Tuscan dish — large rare-cooked T-bone, often shared.'),
  v('la-ribollita', 'la ribollita', 'Tuscan bread-and-bean soup', 'food', 'both', 2, 'tuscany'),
  v('la-pappa-pomodoro', 'la pappa al pomodoro', 'Tuscan tomato-bread soup', 'food', 'both', 2, 'tuscany'),
  v('la-focaccia', 'la focaccia', 'flat oiled bread', 'food', 'both', 1, 'liguria', 'Liguria is the home of focaccia. Plain or with onions/olives.'),
  v('il-pesto', 'il pesto alla genovese', 'Genoese pesto (basil/pine nut/parmesan)', 'food', 'both', 1, 'liguria', "Genoa's signature. With trofie or trenette pasta typically."),
  v('le-trofie', 'le trofie', 'short twisted Ligurian pasta', 'food', 'both', 2, 'liguria'),
  v('i-culurgiones', 'i culurgiones', 'Sardinian filled pasta (potato/mint/cheese)', 'food', 'both', 3, 'sardinia'),
  v('la-bottarga', 'la bottarga', 'cured fish roe (mullet/tuna)', 'food', 'both', 3, 'sardinia', 'Coastal Sardinian specialty, grated over pasta.'),
  v('il-pane-carasau', 'il pane carasau', 'thin Sardinian flatbread', 'food', 'both', 2, 'sardinia'),
  v('il-mirto', 'il mirto', 'myrtle liqueur', 'food', 'both', 2, 'sardinia', 'Sardinian post-meal digestivo, dark or white myrtle berry.'),

  v('caro', 'caro/cara', 'expensive', 'shopping', 'both', 1, undefined, 'Agreement: caro (m) / cara (f). Used as adjective: il vino è caro.'),
  v('economico', 'economico', 'cheap / inexpensive', 'shopping', 'both', 1),
  v('quanto-costa', 'quanto costa?', 'how much does it cost?', 'shopping', 'both', 1),
  v('posso-pagare', 'posso pagare con la carta?', 'can I pay by card?', 'shopping', 'formal', 1),
  v('contanti', 'contanti', 'cash', 'shopping', 'both', 1),
  v('un-sacchetto', 'un sacchetto', 'a (shopping) bag', 'shopping', 'both', 2),
  v('lo-sconto', 'lo sconto', 'discount', 'shopping', 'both', 2),

  v('la-banca', 'la banca', 'bank', 'general', 'both', 1),
  v('il-bagno', 'il bagno', 'bathroom', 'general', 'both', 1, undefined, 'Or "la toilette" in some restaurants.'),
  v('aperto', 'aperto', 'open', 'general', 'both', 1),
  v('chiuso', 'chiuso', 'closed', 'general', 'both', 1),
  v('caldo', 'caldo', 'hot', 'general', 'both', 1),
  v('freddo', 'freddo', 'cold', 'general', 'both', 1),
  v('grande', 'grande', 'big', 'general', 'both', 1),
  v('piccolo', 'piccolo', 'small', 'general', 'both', 1),
  v('bello', 'bello', 'beautiful / nice', 'general', 'both', 1),
  v('buono', 'buono', 'good', 'general', 'both', 1),
  v('male', 'male', 'bad / badly', 'general', 'both', 1),
]
