import type { ContentItem } from './types'

const m = (
  id: string,
  italian: string,
  english: string,
  register: ContentItem['register'],
  difficulty: ContentItem['difficulty'],
  notes?: string
): ContentItem => ({
  id: `medical:${id}`,
  type: 'medical',
  language: 'italian',
  italian,
  english,
  audioUrl: '',
  topic: 'medical',
  register,
  difficulty,
  notes,
})

export const italianMedical: ContentItem[] = [
  m('la-farmacia', 'la farmacia', 'pharmacy', 'both', 1, 'Italian pharmacies (green cross sign) handle minor issues — staff are trained to recommend OTC meds.'),
  m('il-medico', 'il medico', 'doctor', 'both', 1),
  m('lospedale', "l'ospedale", 'hospital', 'both', 1),
  m('il-pronto-soccorso', 'il pronto soccorso', 'emergency room', 'both', 1, 'ER. Free for tourists for genuine emergencies.'),
  m('sono-medico', 'sono medico', 'I am a doctor', 'both', 1, 'Useful in any medical context — gets you taken seriously instantly. "Sono dottoressa" is also acceptable for a female physician but "medico" is gender-neutral and preferred professionally.'),
  m('sto-male', 'sto male', "I don't feel well / I feel sick", 'both', 1),
  m('mi-fa-male', 'mi fa male...', 'my ___ hurts', 'both', 1, 'Add body part: mi fa male la testa (head), lo stomaco (stomach), la gola (throat), la schiena (back).'),
  m('mi-fa-male-testa', 'mi fa male la testa', 'I have a headache', 'both', 1),
  m('mi-fa-male-stomaco', 'mi fa male lo stomaco', 'my stomach hurts', 'both', 1),
  m('ho-la-febbre', 'ho la febbre', 'I have a fever', 'both', 1),
  m('ho-mal-di-gola', 'ho mal di gola', 'I have a sore throat', 'both', 1),
  m('ho-la-tosse', 'ho la tosse', 'I have a cough', 'both', 1),
  m('ho-il-raffreddore', 'ho il raffreddore', 'I have a cold', 'both', 1),
  m('mi-sono-fatto-male', 'mi sono fatta male', 'I hurt myself (f)', 'both', 1, 'Use fatto for masculine, fatta for feminine.'),
  m('sono-allergica-a-medical', 'sono allergica a...', "I'm allergic to... (f)", 'both', 1, 'Common: alla penicillina, al lattosio, al glutine, alle arachidi (peanuts), ai crostacei (shellfish).'),
  m('antinfiammatorio', "un antinfiammatorio", 'an anti-inflammatory', 'both', 2),
  m('antidolorifico', "un antidolorifico", 'a pain reliever', 'both', 2),
  m('antipiretico', "un antipiretico", 'a fever reducer', 'both', 2),
  m('paracetamolo', 'il paracetamolo', 'acetaminophen / paracetamol', 'both', 1, 'EU name for Tylenol active ingredient. "Tachipirina" is the dominant brand.'),
  m('ibuprofene', "l'ibuprofene", 'ibuprofen', 'both', 1, 'Brufen is the dominant brand in Italy.'),
  m('antibiotico', "un antibiotico", 'an antibiotic', 'both', 1, 'Most antibiotics in Italy require prescription.'),
  m('una-ricetta', 'una ricetta', 'a prescription', 'both', 1),
  m('senza-ricetta', 'senza ricetta', 'over-the-counter (no prescription)', 'both', 1),
  m('una-pomata', 'una pomata', 'an ointment / cream', 'both', 2),
  m('un-cerotto', 'un cerotto', 'a band-aid', 'both', 1),
  m('lacqua-ossigenata', "l'acqua ossigenata", 'hydrogen peroxide', 'both', 2),
  m('garza', 'la garza', 'gauze', 'both', 2),
  m('puo-consigliare', 'può consigliarmi qualcosa per...', 'can you recommend something for...?', 'formal', 2, 'For pharmacist consultations.'),
  m('da-quanto-tempo', 'da quanto tempo?', 'for how long?', 'both', 1, 'Pharmacist or doctor will ask about symptom duration.'),
  m('da-tre-giorni', 'da tre giorni', 'for three days', 'both', 1),
  m('un-bicchiere-acqua', 'un bicchiere d\'acqua', 'a glass of water', 'both', 1),
  m('mi-sento-meglio', 'mi sento meglio', 'I feel better', 'both', 1),
  m('mi-sento-peggio', 'mi sento peggio', 'I feel worse', 'both', 1),
]
