import type { ContentItem } from './types'

const p = (
  id: string,
  italian: string,
  english: string,
  topic: string,
  register: ContentItem['register'],
  difficulty: ContentItem['difficulty'],
  region?: ContentItem['region'],
  notes?: string
): ContentItem => ({
  id: `phrase:${topic}:${id}`,
  type: 'phrase',
  language: 'italian',
  italian,
  english,
  audioUrl: '',
  topic,
  register,
  difficulty,
  region,
  notes,
})

export const italianPhrases: ContentItem[] = [
  p('mi-chiamo', 'mi chiamo Elisa', 'my name is Elisa', 'social', 'both', 1),
  p('come-sta', 'come sta?', 'how are you? (formal)', 'social', 'formal', 1, undefined, 'Lei form. Use with strangers, hotel staff.'),
  p('come-stai', 'come stai?', 'how are you? (informal)', 'social', 'informal', 1),
  p('sto-bene', 'sto bene, grazie', "I'm well, thanks", 'social', 'both', 1),
  p('piacere', 'piacere di conoscerla', 'pleased to meet you (formal)', 'social', 'formal', 2, undefined, 'Lei form. With "ti" instead it becomes informal.'),
  p('di-dove-sei', 'di dove sei?', 'where are you from? (informal)', 'social', 'informal', 1),
  p('di-dove-e', "di dov'è?", 'where are you from? (formal)', 'social', 'formal', 2),
  p('sono-americana', 'sono americana', "I'm American (f)", 'social', 'both', 1, undefined, 'For Elisa: americana not americano.'),
  p('vivo-a', 'vivo a Los Angeles', 'I live in Los Angeles', 'social', 'both', 1),
  p('parlo-poco', 'parlo poco italiano', 'I speak a little Italian', 'social', 'both', 1, undefined, 'Useful icebreaker. Italians appreciate the attempt.'),
  p('ho-bisogno-di', 'ho bisogno di...', 'I need...', 'social', 'both', 2),
  p('puo-aiutarmi', 'può aiutarmi?', 'can you help me? (formal)', 'social', 'formal', 1, undefined, 'Lei form. Critical phrase if you are stuck anywhere.'),
  p('non-lo-so', 'non lo so', "I don't know", 'social', 'both', 1),
  p('non-mi-ricordo', 'non mi ricordo', "I don't remember", 'social', 'both', 1),
  p('puo-ripetere', 'può ripetere, per favore?', 'can you repeat, please? (formal)', 'social', 'formal', 1),
  p('piu-lentamente', 'più lentamente, per favore', 'more slowly, please', 'social', 'both', 1),

  p('un-tavolo-due', 'un tavolo per due, per favore', 'a table for two, please', 'restaurant', 'formal', 1),
  p('avete-prenotato', 'avete prenotato?', 'do you have a reservation?', 'restaurant', 'formal', 2, undefined, 'You will hear this from waiters.'),
  p('ho-prenotato', 'ho prenotato per le otto', "I have a reservation for 8 o'clock", 'restaurant', 'formal', 2),
  p('cosa-consiglia', 'cosa consiglia?', 'what do you recommend? (formal)', 'restaurant', 'formal', 2),
  p('vorrei', 'vorrei...', 'I would like...', 'restaurant', 'both', 1, undefined, 'More polite than "voglio". Use this when ordering.'),
  p('per-me', 'per me...', 'for me...', 'restaurant', 'both', 1),
  p('e-il-piatto-tipico', 'è un piatto tipico?', 'is it a typical dish?', 'restaurant', 'both', 2),
  p('di-stagione', 'è di stagione?', 'is it in season?', 'restaurant', 'both', 2, undefined, 'Useful for ordering vegetables/fish — locals respect this question.'),
  p('e-buono', 'è buono', "it's good", 'restaurant', 'both', 1),
  p('era-squisito', 'era squisito', 'it was delicious', 'restaurant', 'both', 2),
  p('il-conto-per-favore', 'il conto, per favore', 'the check, please', 'restaurant', 'formal', 1),
  p('separato', 'conti separati, per favore', 'separate checks, please', 'restaurant', 'formal', 2, undefined, 'Less common in Italy than US — they may resist.'),
  p('mancia', 'tenga il resto', 'keep the change', 'restaurant', 'formal', 2, undefined, 'Italian tipping is minimal — rounding up or saying tenga il resto is enough.'),
  p('sono-allergica-a', 'sono allergica alle noci', "I'm allergic to nuts (f)", 'restaurant', 'both', 1, undefined, 'Replace noci with: arachidi (peanuts), crostacei (shellfish), latticini (dairy), glutine (gluten).'),
  p('senza-glutine', "c'è qualcosa senza glutine?", 'is there anything gluten-free?', 'restaurant', 'both', 2),

  p('ho-prenotazione', 'ho una prenotazione a nome di Fazzari', 'I have a reservation under Fazzari', 'hotel', 'formal', 1),
  p('a-che-ora-colazione', 'a che ora è la colazione?', 'what time is breakfast?', 'hotel', 'formal', 1),
  p('inclusa-prezzo', 'la colazione è inclusa nel prezzo?', 'is breakfast included in the price?', 'hotel', 'formal', 2),
  p('fino-a-che-ora', 'fino a che ora si può fare il check-out?', 'until what time is check-out?', 'hotel', 'formal', 2),
  p('un-asciugamano-piu', 'potrei avere un altro asciugamano?', 'could I get another towel?', 'hotel', 'formal', 2),
  p('non-ce-acqua-calda', "non c'è acqua calda", 'there is no hot water', 'hotel', 'formal', 2),
  p('il-wifi-non-va', 'il wifi non funziona', "the wifi isn't working", 'hotel', 'formal', 1),
  p('mi-puo-chiamare-taxi', 'mi può chiamare un taxi?', 'can you call me a taxi?', 'hotel', 'formal', 1),

  p('un-biglietto-per', 'un biglietto per Firenze, per favore', 'a ticket to Florence, please', 'transport', 'formal', 1),
  p('a-che-ora-parte', 'a che ora parte il prossimo treno?', 'what time does the next train leave?', 'transport', 'formal', 1),
  p('da-che-binario', 'da che binario?', 'from which platform?', 'transport', 'both', 1),
  p('e-questo-il-treno', 'è questo il treno per Roma?', 'is this the train to Rome?', 'transport', 'both', 1),
  p('quanto-tempo-ci-vuole', 'quanto tempo ci vuole?', 'how long does it take?', 'transport', 'both', 1),
  p('alla-stazione', 'alla stazione, per favore', 'to the station, please', 'transport', 'formal', 1, undefined, 'For taxis.'),
  p('al-aeroporto', "all'aeroporto, per favore", 'to the airport, please', 'transport', 'formal', 1),
  p('puo-fermarsi-qui', 'può fermarsi qui?', 'can you stop here? (formal)', 'transport', 'formal', 1),

  p('mi-scusi-dove-e', "mi scusi, dov'è il duomo?", 'excuse me, where is the cathedral?', 'directions', 'formal', 1, undefined, 'Replace duomo with: la stazione, il bagno, la farmacia, etc.'),
  p('come-arrivo-a', 'come arrivo a piazza San Marco?', 'how do I get to St. Mark\'s Square?', 'directions', 'formal', 2),
  p('e-lontano-da-qui', 'è lontano da qui?', 'is it far from here?', 'directions', 'both', 1),
  p('si-puo-andare-a-piedi', 'si può andare a piedi?', 'can one walk there?', 'directions', 'both', 2),
  p('mi-sono-persa', "mi sono persa, può aiutarmi?", "I'm lost, can you help me? (f)", 'directions', 'formal', 2, undefined, 'persa for feminine, perso for masculine.'),

  p('quanto-costa-questo', 'quanto costa questo?', 'how much does this cost?', 'shopping', 'both', 1),
  p('posso-vedere', 'posso vedere?', 'can I see / look?', 'shopping', 'both', 1),
  p('sto-solo-guardando', 'sto solo guardando, grazie', "I'm just looking, thanks", 'shopping', 'both', 1),
  p('paga-con-carta', 'posso pagare con la carta?', 'can I pay by card?', 'shopping', 'formal', 1),
  p('un-sacchetto-per-favore', 'un sacchetto, per favore', 'a bag, please', 'shopping', 'both', 2, undefined, 'Bags cost extra at most stores in Italy now (~10 cents).'),
  p('e-troppo-caro', 'è troppo caro', "it's too expensive", 'shopping', 'both', 1),

  p('e-aperto', 'è aperto?', 'is it open?', 'general', 'both', 1),
  p('a-che-ora-chiude', 'a che ora chiude?', 'what time does it close?', 'general', 'both', 1),
  p('e-libero', 'è libero?', 'is it free / available?', 'general', 'both', 1, undefined, 'For tables, seats, taxis.'),
  p('mi-piace', 'mi piace molto', 'I like it a lot', 'general', 'both', 1, undefined, 'Heritage-speaker note: piacere takes the thing as subject — "mi piace il caffè" not "piaccio il caffè".'),
  p('non-mi-piace', 'non mi piace', "I don't like it", 'general', 'both', 1),
  p('che-bello', 'che bello!', 'how nice / beautiful!', 'general', 'both', 1),
  p('in-bocca-al-lupo', 'in bocca al lupo', 'good luck (lit. "in the wolf\'s mouth")', 'general', 'both', 2, undefined, 'Italian "good luck" — reply with "crepi il lupo" (may the wolf die). Never say "buona fortuna" — superstitious bad form.'),

  p('aiuto', 'aiuto!', 'help!', 'emergency', 'both', 1),
  p('chiami-la-polizia', 'chiami la polizia!', 'call the police! (formal)', 'emergency', 'formal', 1),
  p('chiami-unambulanza', "chiami un'ambulanza!", 'call an ambulance! (formal)', 'emergency', 'formal', 1),
  p('mi-hanno-rubato', 'mi hanno rubato il portafoglio', 'they stole my wallet', 'emergency', 'both', 2),
  p('ho-perso-il-passaporto', 'ho perso il passaporto', 'I lost my passport', 'emergency', 'both', 1),
  p('dov-e-il-consolato', 'dov\'è il consolato americano?', 'where is the American consulate?', 'emergency', 'both', 2),
  p('e-unemergenza', "è un'emergenza", "it's an emergency", 'emergency', 'both', 1),
]
