import type { ContentItem } from './types'

const v = (
  id: string,
  spanish: string,
  english: string,
  topic: string,
  register: ContentItem['register'],
  difficulty: ContentItem['difficulty'],
  notes?: string
): ContentItem => ({
  id: `vocab:${topic}:${id}`,
  type: 'vocab',
  language: 'spanish',
  spanish,
  english,
  audioUrl: '',
  topic,
  register,
  difficulty,
  notes,
})

export const spanishVocab: ContentItem[] = [
  v('hola', 'hola', 'hi / hello', 'greeting', 'both', 1),
  v('buenos-dias', 'buenos días', 'good morning', 'greeting', 'both', 1),
  v('buenas-tardes', 'buenas tardes', 'good afternoon', 'greeting', 'both', 1),
  v('buenas-noches', 'buenas noches', 'good evening / night', 'greeting', 'both', 1),
  v('adios', 'adiós', 'goodbye', 'greeting', 'both', 1),
  v('hasta-luego', 'hasta luego', 'see you later', 'greeting', 'both', 1),
  v('gracias', 'gracias', 'thank you', 'social', 'both', 1),
  v('muchas-gracias', 'muchas gracias', 'thanks a lot', 'social', 'both', 1),
  v('de-nada', 'de nada', "you're welcome", 'social', 'both', 1),
  v('por-favor', 'por favor', 'please', 'social', 'both', 1),
  v('perdon', 'perdón', 'excuse me / sorry', 'social', 'both', 1),
  v('disculpe', 'disculpe', 'excuse me (formal)', 'social', 'formal', 1, 'usted form. Use with strangers, waiters.'),
  v('lo-siento', 'lo siento', "I'm sorry", 'social', 'both', 1),
  v('si-spanish', 'sí', 'yes', 'social', 'both', 1),
  v('no-spanish', 'no', 'no', 'social', 'both', 1),
  v('no-entiendo', 'no entiendo', "I don't understand", 'social', 'both', 1),
  v('habla-ingles', '¿habla inglés?', 'do you speak English?', 'social', 'formal', 1),
  v('como-se-dice', '¿cómo se dice...?', 'how do you say...?', 'social', 'both', 2),

  v('la-cuenta', 'la cuenta', 'the bill / check', 'restaurant', 'both', 1),
  v('una-mesa', 'una mesa para dos', 'a table for two', 'restaurant', 'formal', 1),
  v('el-menu-spanish', 'el menú', 'the menu', 'restaurant', 'both', 1),
  v('el-agua', 'el agua', 'water', 'restaurant', 'both', 1, 'Note: feminine "agua" but takes "el" because of stressed initial a (el agua, las aguas).'),
  v('con-gas', 'con gas', 'sparkling', 'restaurant', 'both', 1),
  v('sin-gas', 'sin gas', 'still', 'restaurant', 'both', 1),
  v('un-cafe-spanish', 'un café', 'a coffee', 'restaurant', 'both', 1),
  v('una-cerveza', 'una cerveza', 'a beer', 'restaurant', 'both', 1),
  v('vino-tinto', 'vino tinto', 'red wine', 'restaurant', 'both', 1, 'Note: tinto, NOT rojo, for red wine in Spanish.'),
  v('vino-blanco', 'vino blanco', 'white wine', 'restaurant', 'both', 1),
  v('soy-alergico', 'soy alérgica a...', "I'm allergic to (f)", 'restaurant', 'both', 1),
  v('vegetariana', 'soy vegetariana', "I'm vegetarian (f)", 'restaurant', 'both', 1),
  v('sin-spanish', 'sin', 'without', 'restaurant', 'both', 1),
  v('para-llevar', 'para llevar', 'to-go', 'restaurant', 'both', 2),

  v('la-llave', 'la llave', 'the key', 'hotel', 'both', 1),
  v('la-habitacion', 'la habitación', 'the room', 'hotel', 'both', 1),
  v('el-desayuno', 'el desayuno', 'breakfast', 'hotel', 'both', 1),
  v('una-reserva', 'una reserva', 'a reservation', 'hotel', 'formal', 1),
  v('el-wifi-spanish', 'el wifi', 'the wifi', 'hotel', 'both', 1),
  v('una-toalla', 'una toalla', 'a towel', 'hotel', 'both', 1),
  v('no-funciona-spanish', 'no funciona', "it doesn't work", 'hotel', 'both', 1),

  v('el-tren', 'el tren', 'train', 'transport', 'both', 1),
  v('un-billete', 'un billete', 'a ticket', 'transport', 'both', 1, 'Spain. In Latin America: un boleto.'),
  v('ida', 'ida', 'one-way', 'transport', 'both', 1),
  v('ida-y-vuelta', 'ida y vuelta', 'round-trip', 'transport', 'both', 1),
  v('el-anden', 'el andén', 'the platform', 'transport', 'both', 1),
  v('un-taxi-spanish', 'un taxi', 'a taxi', 'transport', 'both', 1),
  v('el-autobus', 'el autobús', 'bus', 'transport', 'both', 1),

  v('a-la-derecha', 'a la derecha', 'to the right', 'directions', 'both', 1),
  v('a-la-izquierda', 'a la izquierda', 'to the left', 'directions', 'both', 1),
  v('todo-recto', 'todo recto', 'straight ahead', 'directions', 'both', 1, 'Spain usage. Latin America: todo derecho.'),
  v('cerca', 'cerca', 'near', 'directions', 'both', 1),
  v('lejos', 'lejos', 'far', 'directions', 'both', 1),
  v('aqui', 'aquí', 'here', 'directions', 'both', 1),
  v('alli', 'allí', 'there', 'directions', 'both', 1),
  v('donde-esta', '¿dónde está...?', 'where is...?', 'directions', 'both', 1),

  v('uno-spanish', 'uno', 'one', 'numbers', 'both', 1),
  v('dos-spanish', 'dos', 'two', 'numbers', 'both', 1),
  v('tres-spanish', 'tres', 'three', 'numbers', 'both', 1),
  v('cuatro', 'cuatro', 'four', 'numbers', 'both', 1),
  v('cinco-spanish', 'cinco', 'five', 'numbers', 'both', 1),
  v('seis-spanish', 'seis', 'six', 'numbers', 'both', 1),
  v('siete-spanish', 'siete', 'seven', 'numbers', 'both', 1),
  v('ocho-spanish', 'ocho', 'eight', 'numbers', 'both', 1),
  v('nueve', 'nueve', 'nine', 'numbers', 'both', 1),
  v('diez-spanish', 'diez', 'ten', 'numbers', 'both', 1),
  v('cien', 'cien', 'one hundred', 'numbers', 'both', 1),
  v('mil', 'mil', 'one thousand', 'numbers', 'both', 1),

  v('hoy-spanish', 'hoy', 'today', 'time', 'both', 1),
  v('ayer-spanish', 'ayer', 'yesterday', 'time', 'both', 1),
  v('manana', 'mañana', 'tomorrow / morning', 'time', 'both', 1),
  v('ahora-spanish', 'ahora', 'now', 'time', 'both', 1),
  v('despues', 'después', 'after / later', 'time', 'both', 1),
  v('antes', 'antes', 'before / earlier', 'time', 'both', 1),

  v('caro-spanish', 'caro/cara', 'expensive', 'shopping', 'both', 1),
  v('barato', 'barato/barata', 'cheap', 'shopping', 'both', 1),
  v('cuanto-cuesta', '¿cuánto cuesta?', 'how much does it cost?', 'shopping', 'both', 1),
  v('puedo-pagar', '¿puedo pagar con tarjeta?', 'can I pay by card?', 'shopping', 'formal', 1),
  v('efectivo', 'efectivo', 'cash', 'shopping', 'both', 1),

  v('el-bano', 'el baño', 'bathroom', 'general', 'both', 1),
  v('abierto-spanish', 'abierto', 'open', 'general', 'both', 1),
  v('cerrado', 'cerrado', 'closed', 'general', 'both', 1),

  v('ayuda-spanish', '¡ayuda!', 'help!', 'emergency', 'both', 1),
  v('la-policia', 'la policía', 'police', 'emergency', 'both', 1),
  v('una-ambulancia', 'una ambulancia', 'an ambulance', 'emergency', 'both', 1),
  v('la-farmacia-spanish', 'la farmacia', 'pharmacy', 'emergency', 'both', 1),
  v('soy-medica', 'soy médica', 'I am a doctor (f)', 'emergency', 'both', 1),
  v('me-duele', 'me duele...', 'my ___ hurts', 'emergency', 'both', 1),
  v('la-cabeza', 'la cabeza', 'head', 'emergency', 'both', 1),
  v('el-estomago', 'el estómago', 'stomach', 'emergency', 'both', 1),
]
